apiVersion: v1
kind: Namespace
metadata:
  name: estafette
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: estafette-gcp-service-account
  namespace: estafette
  labels:
    app: estafette-gcp-service-account
    team: ${TEAM_NAME}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: estafette-gcp-service-account
  namespace: estafette
  labels:
    app: estafette-gcp-service-account
    team: ${TEAM_NAME}
spec:
  replicas: 1
  strategy:
    type: Recreate
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: estafette-gcp-service-account
  template:
    metadata:
      labels:
        app: estafette-gcp-service-account
        team: ${TEAM_NAME}
        version: ${VERSION}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9101"
    spec:
      serviceAccount: estafette-gcp-service-account
      terminationGracePeriodSeconds: 120
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 10
            preference:
              matchExpressions:
              - key: cloud.google.com/gke-preemptible
                operator: In
                values:
                - "true"
      containers:
      - name: estafette-gcp-service-account
        image: estafette/estafette-gcp-service-account:${GO_PIPELINE_LABEL}
        imagePullPolicy: IfNotPresent
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /secrets/service-account-key.json
        - name: SERVICE_ACCOUNT_PREFIX
          value: "${SERVICE_ACCOUNT_PREFIX}"
        - name: SERVICE_ACCOUNT_PROJECT_ID
          value: "${SERVICE_ACCOUNT_PROJECT_ID}"
        - name: KEY_ROTATION_AFTER_HOURS
          value: "${KEY_ROTATION_AFTER_HOURS}"
        - name: PURGE_KEYS_AFTER_HOURS
          value: "${PURGE_KEYS_AFTER_HOURS}"
        resources:
          requests:
            cpu: 50m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 250Mi
        livenessProbe:
          httpGet:
            path: /metrics
            port: 9101
          initialDelaySeconds: 30
          timeoutSeconds: 1
        volumeMounts:
        - name: estafette-gcp-service-account-secrets
          mountPath: /secrets
      volumes:
      - name: estafette-gcp-service-account-secrets
        secret:
          secretName: estafette-gcp-service-account-secrets