apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "estafette-gcp-service-account.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "estafette-gcp-service-account.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "estafette-gcp-service-account.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "estafette-gcp-service-account.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        {{- if .Chart.AppVersion }}
        app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
        {{- end }}
        {{- range $key, $value := .Values.extraPodLabels }}
        {{ $key }}: {{ $value }}
        {{- end }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9101"
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ template "estafette-gcp-service-account.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ template "estafette-gcp-service-account.imageTag" . }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.extraArgs }}
          args:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /secrets/service-account-key.json
            - name: MODE
              value: {{ .Values.mode | quote }}
            - name: SERVICE_ACCOUNT_PROJECT_ID
              value: {{ .Values.serviceAccountProjectID | quote }}
            - name: KEY_ROTATION_AFTER_HOURS
              value: {{ .Values.keyRotationAfterHours | quote }}
            - name: PURGE_KEYS_AFTER_HOURS
              value: {{ .Values.purgeKeysAfterHours | quote }}
            - name: ALLOW_DISABLE_KEY_ROTATION_OVERRIDE
              value: {{ .Values.allowDisableKeyRotationOverride | quote }}
            {{- range $key, $value := .Values.extraEnv }}
            - name: {{ $key }}
              value: {{ $value }}
            {{- end }}
          ports:
            - name: metrics
              containerPort: 9101
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /metrics
              port: metrics
            initialDelaySeconds: 30
            timeoutSeconds: 1
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - name: app-secrets
            mountPath: /secrets
      terminationGracePeriodSeconds: 300
      volumes:
      - name: app-secrets
        secret:
          secretName: {{ include "estafette-gcp-service-account.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
