{{- if .Values.rbac.enable -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "estafette-gcp-service-account.fullname" . }}
  labels:
{{ include "estafette-gcp-service-account.labels" . | indent 4 }}
rules:
- apiGroups: [""] # "" indicates the core API group
  resources:
  - secrets
  - serviceaccounts
  verbs:
  - get
  - list
  - update
  - watch
{{- end -}}
