{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "estafette-gcp-service-account.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "estafette-gcp-service-account.labels" . | indent 4 }}
{{- end -}}
